### ISSUE TITLE
Pressing left or right on a Android TV Remote does not rewind or forward

### ISSUE THREAD

**Issue by Derekku18** [kemuriXD/SaikouTV#2]
### Summary

Pressing left or right on a Android TV Remote does not rewind or forward. It also does not rewind or forward if you hold left or right.

### Reproduction Steps

Try to rewind or forward using left or right on a Android TV Remote. I used an Nvidia Shield TV Remote.

### Expected Result

When pressing left, it should rewind by a certain amount.
When pressing right, it should forward by a certain amount.
When holding left, it should continuously rewind until the user lets go of the left button.
When holding right, it should continuously forward until the user lets go of the right button.

### Actual Result

Nothing happens.

### Device Information

Saikou Version: 1.1.1
Brand: Nvidia Shield Pro

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by amiraizat124** [comment]
@Derekku18, temporary solution for this bug.
You can press left or right on an Android TV Remote directly without pressing OK to bring out the control menu.

Mine works, if I do not press the OK button first. Just directly press the left/right button.

**Comment by kemuriXD** [comment]
Hi,

ExoPlayer is outdated on the TV version and needs a s*** tonne of reworking for it to be better than it currently is. With the lack of knowledge around ExoPlayer and Kotlin it's very difficult for me.

Nanoc **may** or may not come back and fix a few things. We're not sure yet. Nevertheless thanks for raising an issue.

Kemuri
