### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by anime-src** [kemuriXD/SaikouTV#6]
### Summary

Can't update from version 1.1.1 to 1.1.2

### Reproduction Steps

Download latest version and try to do update of existing version

### Expected Result

Should update

### Actual Result

Got message App not installed as package conflicts with an existing package, can we make this update process not painfull, i need to uninatall old version then install new one and do the tv login, i think package name is again different the previous version package

### Device Information

Saikou version: 1.1.1
Device: Chromecast 4k

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by kemuriXD** [comment]
Noted, will be addressed in the next update (if there will be one)
