### ISSUE TITLE
UI Optimization

### ISSUE THREAD

**Issue by ANASXOP** [kemuriXD/SaikouTV#7]
### Summary

Make it a bit more optimise for tv.

### The Problem

there's always a lag when i use saikou on tv and also there are some subtitle issues in kaido  server when i try to load subtitle in kaido server it's never load. I want you to look into it.

### The Ideal Solution

Make UI a bit more fast and optimise it for tv. it  also lag when i select the server and also theres a lag

**Comment by kemuriXD** [comment]
Hi,

I currently only update sources when possible. And due to the DMCA notice that has been issued on Saikou, we've also ceased overall development and are complying with the notice to prevent further legal troubles.

Thanks for your understanding,

Kemuri
